import { Router } from "express";
import { adminRouter } from "../modules/admin/admin.routes";
import { authRouter } from "../modules/auth/auth.routes";
import { twoFactorRouter } from "../modules/auth/two-factor.routes";
import { catalogRouter } from "../modules/catalog/catalog.routes";
import { conversationsRouter } from "../modules/conversations/conversations.routes";
import { disputesRouter } from "../modules/disputes/disputes.routes";
import { healthRouter } from "../modules/health/health.routes";
import { homeRouter } from "../modules/home/home.routes";
import { jobsRouter } from "../modules/jobs/jobs.routes";
import { listingsRouter } from "../modules/listings/listings.routes";
import { mediaRouter } from "../modules/media/media.routes";
import { notificationsRouter } from "../modules/notifications/notifications.routes";
import { ordersRouter } from "../modules/orders/orders.routes";
import { paymentsRouter } from "../modules/payments/payments.routes";
import { questionsRouter } from "../modules/questions/questions.routes";
import { reviewsRouter } from "../modules/reviews/reviews.routes";
import { walletRouter } from "../modules/wallet/wallet.routes";
import { payoutsRouter } from "../modules/wallet/payouts.routes";
import { favoritesRouter } from "../modules/favorites/favorites.routes";
import { dashboardRouter } from "../modules/dashboard/dashboard.routes";
import { profilesRouter } from "../modules/profiles/profiles.routes";
import { kycRouter } from "../modules/kyc/kyc.routes";
import { visibilityRouter } from "../modules/visibility/visibility.routes";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/auth/2fa", twoFactorRouter);
apiRouter.use("/catalog", catalogRouter);
apiRouter.use("/home", homeRouter);
apiRouter.use("/visibility", visibilityRouter);
apiRouter.use("/media", mediaRouter);
apiRouter.use("/listings", listingsRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/orders", ordersRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/wallet", walletRouter);
apiRouter.use("/payouts", payoutsRouter);
apiRouter.use("/favorites", favoritesRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/conversations", conversationsRouter);
apiRouter.use("/disputes", disputesRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/questions", questionsRouter);
apiRouter.use("/reviews", reviewsRouter);
apiRouter.use("/profiles", profilesRouter);
apiRouter.use("/kyc", kycRouter);
apiRouter.use("/jobs", jobsRouter);
