import { Router } from "express";
import { adminAuthRouter } from "../admin-auth/admin-auth.routes";
import { listingsAdminRouter } from "../listings/listings.admin.routes";
import { requireAdminAuth } from "../../middleware/admin-auth";
import { adminStatsRouter } from "./admin-stats.routes";
import { adminDisputesRouter } from "./admin-disputes.routes";
import { adminUsersRouter } from "./admin-users.routes";
import { adminOrdersRouter } from "./admin-orders.routes";
import { adminFinanceRouter } from "./admin-finance.routes";
import { adminAuditRouter } from "./admin-audit.routes";
import { adminCategoriesRouter } from "./admin-categories.routes";
import { adminMediaRouter } from "./admin-media.routes";
import { adminChatsRouter } from "./admin-chats.routes";
import { adminVisibilityRouter } from "./admin-visibility.routes";
import { adminHomeSectionsRouter } from "./admin-home-sections.routes";

export const adminRouter = Router();

adminRouter.use("/auth", adminAuthRouter);
adminRouter.use(requireAdminAuth);
adminRouter.use("/stats", adminStatsRouter);
adminRouter.use("/listings", listingsAdminRouter);
adminRouter.use("/disputes", adminDisputesRouter);
adminRouter.use("/users", adminUsersRouter);
adminRouter.use("/orders", adminOrdersRouter);
adminRouter.use("/finance", adminFinanceRouter);
adminRouter.use("/audit", adminAuditRouter);
adminRouter.use("/categories", adminCategoriesRouter);
adminRouter.use("/media", adminMediaRouter);
adminRouter.use("/chats", adminChatsRouter);
adminRouter.use("/visibility", adminVisibilityRouter);
adminRouter.use("/home-sections", adminHomeSectionsRouter);
